services:
  # Full-Stack Service (Backend + Frontend)
  - type: web
    name: projectpro-fullstack
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: mysql://root:dBNPUXyPCjLweRqziukZKQMAOjXFEtzx@mainline.proxy.rlwy.net:19492/railway
      - key: PORT
        value: 3000
      - key: SESSION_SECRET
        value: your-super-secret-session-key-for-production
